### PR TITLE
BDESK-12492_Integrate Gitleaks in CI process for other BoldDesk repos

### PR DESCRIPTION
**Pull request by Vikram-Raghu**
## Feature description
* Integrated Gitleaks in CI process of code-samples

##  Analysis and design
NA

## Solution Description
* `build/build.cake` - added new GitLeaks Task to show secret results.
* `gitleaks.toml` - added new toml file to define secret scanning rules

## Areas affected and ensured
NA

## Is this Featured is Automated ?
NA
  
### How many unit test cases written ?
NA

### How many integration test cases written ?  
NA

### Reason for not automated 
NA

## Additional checklist

* Is there any existing behavior change due to this code changes? - No
* Any new content used, if so is that added in resource file? - Yes, added code to Execute `GitLeaks` and show the count in `build/build.cake` file and `gitleaks.toml` file to define the scanning rules.

### CODE REVIEW

**Comment by Edberg-Vasan** [comment]
rebuild

**Comment by Edberg-Vasan** [comment]
rebuild

**Comment by Edberg-Vasan** [comment]
rebuild

**Review by kailashp2289 — APPROVED** [review]
@bharatdwarkanim - changes are fine, you can merge

**Pull request merged**
